apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: newnginx
      app.kubernetes.io/component: newnginx
      app.kubernetes.io/instance: newnginx
    name: newnginx
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/bitnami/nginx
      from:
        kind: DockerImage
        name: quay.io/bitnami/nginx
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"newnginx:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"newnginx\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: newnginx
      app.kubernetes.io/component: newnginx
      app.kubernetes.io/instance: newnginx
    name: newnginx
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: newnginx
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: newnginx
      spec:
        containers:
        - image: ' '
          name: newnginx
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: newnginx
      app.kubernetes.io/component: newnginx
      app.kubernetes.io/instance: newnginx
    name: newnginx
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: newnginx
  status:
    loadBalancer: {}
kind: List
metadata: {}
