apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: branch
      app.kubernetes.io/component: branch
      app.kubernetes.io/instance: branch
    name: branch
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: branch:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: beta4
        uri: https://github.com/openshift/ruby-hello-world.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ruby-22-centos7:latest
      type: Docker
    triggers:
    - github:
        secret: 8J_o0Wrrg9v7FNUod6jp
      type: GitHub
    - generic:
        secret: q1O1BBqfNorNNmtnAL9b
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"branch:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"branch\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: branch
      app.kubernetes.io/component: branch
      app.kubernetes.io/instance: branch
    name: branch
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: branch
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: branch
      spec:
        containers:
        - image: ' '
          name: branch
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: branch
      app.kubernetes.io/component: branch
      app.kubernetes.io/instance: branch
    name: branch
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: branch
  status:
    loadBalancer: {}
kind: List
metadata: {}
